
export const ARTISTS_FETCH_REQUEST = "ARTISTS_FETCH_REQUEST";
export const ARTISTS_FETCH_SUCCESS = "ARTISTS_FETCH_SUCCESS";
export const ARTISTS_FETCH_FAILURE = "ARTISTS_FETCH_FAILURE";

export const ARTIST_FETCH_REQUEST = "ARTIST_FETCH_REQUEST";
export const ARTIST_FETCH_SUCCESS = "ARTIST_FETCH_SUCCESS";
export const ARTIST_FETCH_FAILURE = "ARTIST_FETCH_FAILURE";

export const ARTIST_DELETE_REQUEST = "ARTIST_DELETE_REQUEST";
export const ARTIST_DELETE_SUCCESS = "ARTIST_DELETE_SUCCESS";
export const ARTIST_DELETE_FAILURE = "ARTIST_DELETE_FAILURE";

export const ARTIST_PUBLISH_FAILURE = "ARTIST_PUBLISH_FAILURE";

export const ARTIST_TRACKS_FETCH_REQUEST = "ARTIST_TRACKS_FETCH_REQUEST";
export const ARTIST_TRACKS_FETCH_SUCCESS = "ARTIST_TRACKS_FETCH_SUCCESS";
export const ARTIST_TRACKS_FETCH_FAILURE = "ARTIST_TRACKS_FETCH_FAILURE";

export const ARTIST_TRACKS_DELETE_FAILURE = "ARTIST_TRACKS_DELETE_FAILURE";

export const ARTIST_TRACKS_PUBLISH_FAILURE = "ARTIST_TRACKS_PUBLISH_FAILURE";

export const ARTIST_CREATE_REQUEST = "ARTIST_CREATE_REQUEST";
export const ARTIST_CREATE_SUCCESS = "ARTIST_CREATE_SUCCESS";
export const ARTIST_CREATE_FAILURE = "ARTIST_CREATE_FAILURE";

export const ARTIST_ALBUMS_FETCH_REQUEST = "ARTIST_ALBUMS_FETCH_REQUEST";
export const ARTIST_ALBUMS_FETCH_SUCCESS = "ARTIST_ALBUMS_FETCH_SUCCESS";
export const ARTIST_ALBUMS_FETCH_FAILURE = "ARTIST_ALBUMS_FETCH_FAILURE";

export const ALBUMS_FETCH_REQUEST = "ALBUMS_FETCH_REQUEST";
export const ALBUMS_FETCH_SUCCESS = "ALBUMS_FETCH_SUCCESS";
export const ALBUMS_FETCH_FAILURE = "ALBUMS_FETCH_FAILURE";

export const ALBUM_FETCH_REQUEST = "ALBUM_FETCH_REQUEST";
export const ALBUM_FETCH_SUCCESS = "ALBUM_FETCH_SUCCESS";
export const ALBUM_FETCH_FAILURE = "ALBUM_FETCH_FAILURE";

export const ALBUM_PUBLISH_FAILURE = "ALBUM_PUBLISH_FAILURE";

export const ALBUM_DELETE_REQUEST = "ALBUM_DELETE_REQUEST";
export const ALBUM_DELETE_SUCCESS = "ALBUM_DELETE_SUCCESS";
export const ALBUM_DELETE_FAILURE = "ALBUM_DELETE_FAILURE";

export const ALBUM_CREATE_REQUEST = "ALBUM_CREATE_REQUEST";
export const ALBUM_CREATE_SUCCESS = "ALBUM_CREATE_SUCCESS";
export const ALBUM_CREATE_FAILURE = "ALBUM_CREATE_FAILURE";

export const ALBUM_TRACKS_FETCH_REQUEST = "ALBUM_TRACKS_FETCH_REQUEST";
export const ALBUM_TRACKS_FETCH_SUCCESS = "ALBUM_TRACKS_FETCH_SUCCESS";
export const ALBUM_TRACKS_FETCH_FAILURE = "ALBUM_TRACKS_FETCH_FAILURE";

export const ALBUM_TRACKS_DELETE_FAILURE = "ALBUM_TRACKS_DELETE_FAILURE";

export const ALBUM_TRACKS_PUBLISH_FAILURE = "ALBUM_TRACKS_PUBLISH_FAILURE";

export const TRACK_CREATE_REQUEST = "TRACK_CREATE_REQUEST";
export const TRACK_CREATE_SUCCESS = "TRACK_CREATE_SUCCESS";
export const TRACK_CREATE_FAILURE = "TRACK_CREATE_FAILURE";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";

export const ADD_TRACK_TO_HISTORY_REQUEST = "ADD_TRACK_TO_HISTORY_REQUEST";
export const ADD_TRACK_TO_HISTORY_SUCCESS = "ADD_TRACK_TO_HISTORY_SUCCESS";
export const ADD_TRACK_TO_HISTORY_FAILURE = "ADD_TRACK_TO_HISTORY_FAILURE";

export const FETCH_TRACK_HISTORY_REQUEST = "FETCH_TRACK_HISTORY_REQUEST";
export const FETCH_TRACK_HISTORY_SUCCESS = "FETCH_TRACK_HISTORY_SUCCESS";
export const FETCH_TRACK_HISTORY_FAILURE = "FETCH_TRACK_HISTORY_FAILURE";

export const ADD_TO_FAVORITE_REQUEST = "ADD_TO_FAVORITE_REQUEST";
export const ADD_TO_FAVORITE_SUCCESS = "ADD_TO_FAVORITE_SUCCESS";
export const ADD_TO_FAVORITE_FAILURE = "ADD_TO_FAVORITE_FAILURE";

export const USER_FETCH_REQUEST = "USER_FETCH_REQUEST";
export const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS";
export const USER_FETCH_FAILURE = "USER_FETCH_FAILURE";